version: "3"
services:
  db:
    build: "./database"
    container_name: "my_postgres"
    ports:
      - "54320:5432"
    environment:
      - POSTGRES_DB:library
      - POSTGRES_USER:postgres
      - POSTGRES_PASSWORD:pg
    volumes:
      - my_dbdata:/var/lib/postgresqlnew/data
      - ./database/dump.sql:/docker-entrypoint-initdb.d/dump.sql
volumes:
  my_dbdata:
